//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomSurveyorr..Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RoomSurveyorRH6.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap OrientPoly_Icon {
            get {
                object obj = ResourceManager.GetObject("OrientPoly_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoomSurvey1_Icon {
            get {
                object obj = ResourceManager.GetObject("RoomSurvey1_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoomSurvey2_Icon {
            get {
                object obj = ResourceManager.GetObject("RoomSurvey2_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoomSurvey_Icon {
            get {
                object obj = ResourceManager.GetObject("RoomSurvey_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoomSurvey3_Icon {
            get {
                object obj = ResourceManager.GetObject("RoomSurvey3_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WnInside_Icon {
            get {
                object obj = ResourceManager.GetObject("WnInside_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IsOrtho_Icon {
            get {
                object obj = ResourceManager.GetObject("IsOrtho_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IsConvex_Icon {
            get {
                object obj = ResourceManager.GetObject("IsConvex_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Angles_Icon {
            get {
                object obj = ResourceManager.GetObject("Angles_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShiftPolySPt_Icon {
            get {
                object obj = ResourceManager.GetObject("ShiftPolySPt_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoomSurvey4_Icon {
            get {
                object obj = ResourceManager.GetObject("RoomSurvey4_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoomTurtle_Icon {
            get {
                object obj = ResourceManager.GetObject("RoomTurtle_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ArePointsLeft_Icon {
            get {
                object obj = ResourceManager.GetObject("ArePointsLeft_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CornerProperties_Icon {
            get {
                object obj = ResourceManager.GetObject("CornerProperties_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeOgonizer_Icon {
            get {
                object obj = ResourceManager.GetObject("DeOgonizer_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeOgonizer_v1_Icon {
            get {
                object obj = ResourceManager.GetObject("DeOgonizer_v1_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeOgonizer_v2_Icon {
            get {
                object obj = ResourceManager.GetObject("DeOgonizer_v2_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeOgonizer_v3_Icon {
            get {
                object obj = ResourceManager.GetObject("DeOgonizer_v3_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeOgonizer_v4_Icon {
            get {
                object obj = ResourceManager.GetObject("DeOgonizer_v4_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InternalDiagonals_Icon {
            get {
                object obj = ResourceManager.GetObject("InternalDiagonals_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap IsPointLeft_Icon {
            get {
                object obj = ResourceManager.GetObject("IsPointLeft_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PolyDiagonals_Icon {
            get {
                object obj = ResourceManager.GetObject("PolyDiagonals_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PolyDiagonals2_Icon {
            get {
                object obj = ResourceManager.GetObject("PolyDiagonals2_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RandomConvexPoly_Icon {
            get {
                object obj = ResourceManager.GetObject("RandomConvexPoly_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RandomOgon_Icon {
            get {
                object obj = ResourceManager.GetObject("RandomOgon_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoomSurveyOrtho_Icon {
            get {
                object obj = ResourceManager.GetObject("RoomSurveyOrtho_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoomSurveyStrict_Icon {
            get {
                object obj = ResourceManager.GetObject("RoomSurveyStrict_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RS_OnSpeeds_Icon {
            get {
                object obj = ResourceManager.GetObject("RS_OnSpeeds_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoomSurveyor_A_Icon {
            get {
                object obj = ResourceManager.GetObject("RoomSurveyor_A_Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
